# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lenovo\Desktop\PYTHON OTOMOSYON\Todo_App\add_task.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(580, 500)
        Dialog.setMinimumSize(QtCore.QSize(580, 500))
        Dialog.setMaximumSize(QtCore.QSize(800, 500))
        Dialog.setStyleSheet("background-color: rgb(239, 255, 254);")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setContentsMargins(7, -1, -1, -1)
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(300, 30))
        self.label.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.txt_task_title = QtWidgets.QLineEdit(Dialog)
        self.txt_task_title.setMinimumSize(QtCore.QSize(350, 60))
        self.txt_task_title.setMaximumSize(QtCore.QSize(800, 60))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(25)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.txt_task_title.setFont(font)
        self.txt_task_title.setStyleSheet("\n"
":hover { background-color: white;}")
        self.txt_task_title.setText("")
        self.txt_task_title.setMaxLength(12)
        self.txt_task_title.setObjectName("txt_task_title")
        self.verticalLayout_4.addWidget(self.txt_task_title)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_5.addWidget(self.line_2)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setMinimumSize(QtCore.QSize(300, 30))
        self.label_2.setMaximumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.txt_task_detail = QtWidgets.QPlainTextEdit(Dialog)
        self.txt_task_detail.setMinimumSize(QtCore.QSize(350, 250))
        self.txt_task_detail.setMaximumSize(QtCore.QSize(800, 280))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.txt_task_detail.setFont(font)
        self.txt_task_detail.setStyleSheet(":hover { background-color: white;}")
        self.txt_task_detail.setPlainText("")
        self.txt_task_detail.setObjectName("txt_task_detail")
        self.verticalLayout_5.addWidget(self.txt_task_detail)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(-1, 0, 7, 0)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(180, 20))
        self.label_4.setMaximumSize(QtCore.QSize(180, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.start_time = QtWidgets.QDateEdit(Dialog)
        self.start_time.setMinimumSize(QtCore.QSize(180, 50))
        self.start_time.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_time.setFont(font)
        self.start_time.setWrapping(False)
        self.start_time.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.start_time.setCalendarPopup(True)
        self.start_time.setCurrentSectionIndex(0)
        self.start_time.setDate(QtCore.QDate(2019, 1, 1))
        self.start_time.setObjectName("start_time")
        self.verticalLayout_2.addWidget(self.start_time)
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setMinimumSize(QtCore.QSize(180, 20))
        self.label_6.setMaximumSize(QtCore.QSize(180, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(10)
        font.setItalic(False)
        font.setUnderline(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.end_time = QtWidgets.QDateEdit(Dialog)
        self.end_time.setMinimumSize(QtCore.QSize(180, 50))
        self.end_time.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.end_time.setFont(font)
        self.end_time.setCalendarPopup(True)
        self.end_time.setCurrentSectionIndex(0)
        self.end_time.setDate(QtCore.QDate(2019, 1, 1))
        self.end_time.setObjectName("end_time")
        self.verticalLayout_2.addWidget(self.end_time)
        self.important_level = QtWidgets.QComboBox(Dialog)
        self.important_level.setMinimumSize(QtCore.QSize(180, 50))
        self.important_level.setMaximumSize(QtCore.QSize(180, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.important_level.setFont(font)
        self.important_level.setObjectName("important_level")
        self.important_level.addItem("")
        self.important_level.setItemText(0, "Çok Önemli")
        self.important_level.addItem("")
        self.important_level.addItem("")
        self.important_level.addItem("")
        self.verticalLayout_2.addWidget(self.important_level)
        self.btn_ekle = QtWidgets.QPushButton(Dialog)
        self.btn_ekle.setMinimumSize(QtCore.QSize(0, 110))
        self.btn_ekle.setMaximumSize(QtCore.QSize(16777215, 160))
        font = QtGui.QFont()
        font.setFamily("Gabriola")
        font.setPointSize(45)
        self.btn_ekle.setFont(font)
        self.btn_ekle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ekle.setStyleSheet("background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(175, 255, 255, 255), stop:0.845771 rgba(245, 255, 255, 255));\n"
"\n"
"color: rgb(104, 118, 117);")
        self.btn_ekle.setObjectName("btn_ekle")
        self.verticalLayout_2.addWidget(self.btn_ekle)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Görev Ekle"))
        self.label.setText(_translate("Dialog", "KONU BAŞLIĞI"))
        self.label_2.setText(_translate("Dialog", "KONU İÇERİĞİ"))
        self.label_4.setText(_translate("Dialog", "Başlangıç Tarihi"))
        self.label_6.setText(_translate("Dialog", "Bitiş Tarihi"))
        self.important_level.setCurrentText(_translate("Dialog", "Çok Önemli"))
        self.important_level.setItemText(1, _translate("Dialog", "Önemli"))
        self.important_level.setItemText(2, _translate("Dialog", "Önemsiz"))
        self.important_level.setItemText(3, _translate("Dialog", "Çok Önemsiz"))
        self.btn_ekle.setText(_translate("Dialog", "EKLE"))

