# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Lenovo\Desktop\PYTHON OTOMOSYON\Todo_App\todo_App_main.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 600)
        Dialog.setMinimumSize(QtCore.QSize(740, 600))
        Dialog.setMaximumSize(QtCore.QSize(800, 1200))
        Dialog.setMouseTracking(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setMaximumSize(QtCore.QSize(1200, 1200))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(242, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(242, 255, 253))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.tabWidget.setFont(font)
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setToolTip("")
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("font-size:25px;\n"
"background-color: rgb(242, 255, 253);")
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setElideMode(QtCore.Qt.ElideRight)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tabWidgetPage1 = QtWidgets.QWidget()
        self.tabWidgetPage1.setObjectName("tabWidgetPage1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tabWidgetPage1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tv = QtWidgets.QTableView(self.tabWidgetPage1)
        self.tv.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tv.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tv.setToolTip("")
        self.tv.setStatusTip("")
        self.tv.setWhatsThis("")
        self.tv.setAccessibleName("")
        self.tv.setAccessibleDescription("")
        self.tv.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tv.setObjectName("tv")
        self.horizontalLayout.addWidget(self.tv)
        self.tabWidget.addTab(self.tabWidgetPage1, "")
        self.tabWidgetPage2 = QtWidgets.QWidget()
        self.tabWidgetPage2.setObjectName("tabWidgetPage2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.tabWidgetPage2)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tv2 = QtWidgets.QTableView(self.tabWidgetPage2)
        self.tv2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tv2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tv2.setToolTip("")
        self.tv2.setStatusTip("")
        self.tv2.setWhatsThis("")
        self.tv2.setAccessibleName("")
        self.tv2.setAccessibleDescription("")
        self.tv2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tv2.setObjectName("tv2")
        self.horizontalLayout_6.addWidget(self.tv2)
        self.tabWidget.addTab(self.tabWidgetPage2, "")
        self.tabWidgetPage3 = QtWidgets.QWidget()
        self.tabWidgetPage3.setObjectName("tabWidgetPage3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.tabWidgetPage3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tv3 = QtWidgets.QTableView(self.tabWidgetPage3)
        self.tv3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tv3.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tv3.setToolTip("")
        self.tv3.setStatusTip("")
        self.tv3.setWhatsThis("")
        self.tv3.setAccessibleName("")
        self.tv3.setAccessibleDescription("")
        self.tv3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tv3.setObjectName("tv3")
        self.horizontalLayout_2.addWidget(self.tv3)
        self.tabWidget.addTab(self.tabWidgetPage3, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_gorevEkle = QtWidgets.QPushButton(Dialog)
        self.btn_gorevEkle.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_gorevEkle.setFont(font)
        self.btn_gorevEkle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gorevEkle.setStyleSheet("\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(175, 255, 255, 255), stop:0.845771 rgba(245, 255, 255, 255));\n"
"color: rgb(45, 59, 62);")
        self.btn_gorevEkle.setIconSize(QtCore.QSize(80000, 10000))
        self.btn_gorevEkle.setShortcut("")
        self.btn_gorevEkle.setAutoRepeat(False)
        self.btn_gorevEkle.setAutoDefault(False)
        self.btn_gorevEkle.setDefault(True)
        self.btn_gorevEkle.setFlat(False)
        self.btn_gorevEkle.setObjectName("btn_gorevEkle")
        self.horizontalLayout_3.addWidget(self.btn_gorevEkle)
        self.btn_gorev_sil = QtWidgets.QPushButton(Dialog)
        self.btn_gorev_sil.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_gorev_sil.setFont(font)
        self.btn_gorev_sil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_gorev_sil.setStyleSheet("\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(175, 255, 255, 255), stop:0.845771 rgba(245, 255, 255, 255));\n"
"color: rgb(45, 59, 62);")
        self.btn_gorev_sil.setIconSize(QtCore.QSize(80000, 10000))
        self.btn_gorev_sil.setShortcut("")
        self.btn_gorev_sil.setAutoRepeat(False)
        self.btn_gorev_sil.setAutoDefault(False)
        self.btn_gorev_sil.setDefault(True)
        self.btn_gorev_sil.setFlat(False)
        self.btn_gorev_sil.setObjectName("btn_gorev_sil")
        self.horizontalLayout_3.addWidget(self.btn_gorev_sil)
        self.btn_tumunu_sil = QtWidgets.QPushButton(Dialog)
        self.btn_tumunu_sil.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.btn_tumunu_sil.setFont(font)
        self.btn_tumunu_sil.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_tumunu_sil.setStyleSheet("\n"
"background-color: qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(175, 255, 255, 255), stop:0.845771 rgba(245, 255, 255, 255));\n"
"color: rgb(45, 59, 62);")
        self.btn_tumunu_sil.setIconSize(QtCore.QSize(80000, 10000))
        self.btn_tumunu_sil.setShortcut("")
        self.btn_tumunu_sil.setAutoRepeat(False)
        self.btn_tumunu_sil.setAutoDefault(False)
        self.btn_tumunu_sil.setDefault(True)
        self.btn_tumunu_sil.setFlat(False)
        self.btn_tumunu_sil.setObjectName("btn_tumunu_sil")
        self.horizontalLayout_3.addWidget(self.btn_tumunu_sil)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Yapılacaklar"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage1), _translate("Dialog", "Tüm Görevler"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage2), _translate("Dialog", "Devam Eden Görevler"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabWidgetPage3), _translate("Dialog", "Geçmiş Görevler"))
        self.btn_gorevEkle.setText(_translate("Dialog", "Görev Ekle"))
        self.btn_gorev_sil.setText(_translate("Dialog", "Görev Sil"))
        self.btn_tumunu_sil.setText(_translate("Dialog", "Tümünü Sil"))

